# Generated by Django 5.1.2 on 2024-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=10)),
                ('diseno', models.CharField(max_length=10)),
                ('fecha_entrega', models.CharField(max_length=20)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('tamano', models.CharField(max_length=100)),
            ],
        ),
    ]
