# Generated by Django 5.1 on 2024-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_entrega',
            field=models.DateField(max_length=20),
        ),
    ]
