# Generated by Django 5.1.2 on 2024-11-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('codigo_venta', models.CharField(max_length=9)),
                ('n_cliente', models.IntegerField()),
                ('fecha_venta', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=100)),
                ('n_producto', models.IntegerField()),
                ('tipo_pago', models.CharField(max_length=20)),
            ],
        ),
    ]
