# Generated by Django 5.1 on 2024-11-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0002_alter_venta_id_venta_alter_venta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(max_length=20),
        ),
    ]
