# Generated by Django 5.1.2 on 2024-11-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_resgistro',
            new_name='fecha_registro',
        ),
    ]
