# Generated by Django 5.1.2 on 2024-11-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('gmail', models.CharField(max_length=20)),
                ('raiting', models.PositiveSmallIntegerField()),
                ('registro_fecha', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=30)),
            ],
        ),
    ]
