# Generated by Django 5.1 on 2024-11-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0003_alter_proveedor_id_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='raiting',
            field=models.FloatField(),
        ),
    ]
