# Generated by Django 5.1.2 on 2024-11-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=20)),
                ('encargado', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
