# Generated by Django 5.1 on 2024-11-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
